version: "3"
services:
  api:
    image: node:latest
    ports:
      - "3000:3000"
    links:
      - mongo
    command: bash -c "npm run start"
    working_dir: /api
    volumes:
      - .:/api
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"